services:
  agent-distribution-service:
    image: ghcr.io/giveth/agent-distribution-service:latest
    container_name: agent-distribution-service
    ports:
      - "3000:3000"
    env_file:
      - .env
    volumes:
      - ./certs:/usr/src/app/certs:ro
    networks:
      - agent-distribution-service
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  agent-distribution-service:
    external: true
